# Generated by Django 2.2.1 on 2019-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190521_0142'),
        ('students', '0009_auto_20190515_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allopencourses',
            name='schedule',
        ),
        migrations.AddField(
            model_name='allopencourses',
            name='day_hour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opencoursesforyou',
            name='day_hour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='opencoursesforyou',
            name='schedule',
        ),
        migrations.AddField(
            model_name='opencoursesforyou',
            name='schedule',
            field=models.ManyToManyField(default=None, to='schedule.Schedule'),
        ),
    ]
