# Generated by Django 2.2.1 on 2019-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190520_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='opencourse',
        ),
        migrations.AddField(
            model_name='schedule',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
